# Generated by Django 3.2.25 on 2025-11-05 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0008_scheduledcommand'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Firmware version name (e.g., v1.2.3)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of changes in this version')),
                ('firmware_file', models.FileField(help_text='Upload .bin firmware file', upload_to='firmware/')),
                ('device_type', models.CharField(choices=[('esp32', 'ESP32'), ('esp8266', 'ESP8266'), ('esp', 'ESP Generic')], help_text='Compatible device type', max_length=20)),
                ('version_number', models.CharField(help_text='Version number (e.g., 1.2.3)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this version is available for updates')),
                ('file_size', models.IntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, help_text='SHA256 checksum of firmware file', max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTAUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Update progress (0-100)')),
                ('error_message', models.TextField(blank=True, help_text='Error details if update failed')),
                ('previous_version', models.CharField(blank=True, help_text='Previous firmware version', max_length=50)),
                ('update_log', models.JSONField(blank=True, default=list, help_text='Detailed update log')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ota_updates', to='devices.device')),
                ('firmware_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ota_update.firmwareversion')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceFirmwareInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_version', models.CharField(blank=True, help_text='Current firmware version', max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('update_available', models.BooleanField(default=False)),
                ('auto_update_enabled', models.BooleanField(default=False, help_text='Enable automatic updates')),
                ('last_check', models.DateTimeField(blank=True, help_text='Last time checked for updates', null=True)),
                ('available_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ota_update.firmwareversion')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_info', to='devices.device')),
            ],
        ),
        migrations.AddIndex(
            model_name='otaupdate',
            index=models.Index(fields=['device', '-initiated_at'], name='ota_update__device__2187d4_idx'),
        ),
        migrations.AddIndex(
            model_name='otaupdate',
            index=models.Index(fields=['status', '-initiated_at'], name='ota_update__status_2c2258_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='firmwareversion',
            unique_together={('version_number', 'device_type')},
        ),
    ]
