# Generated by Django 3.2.25 on 2025-06-02 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('device_status', models.CharField(default='offline', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_interval', models.IntegerField(default=5)),
                ('device_type', models.CharField(choices=[('esp', 'ESP'), ('lora', 'LoRa'), ('esp8266', 'ESP8266'), ('esp32', 'ESP32'), ('arduino', 'Arduino'), ('raspberry_pi', 'Raspberry Pi')], max_length=20)),
                ('last_status', models.CharField(blank=True, max_length=20, null=True)),
                ('status_change_count', models.IntegerField(default=0)),
                ('status_last_changed', models.DateTimeField(default=django.utils.timezone.now)),
                ('settings', djongo.models.fields.JSONField(blank=True, default=dict, null=True)),
                ('pending_status', models.CharField(blank=True, max_length=20, null=True)),
                ('pending_status_time', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('all', 'All Updates'), ('status_change', 'Status Changes Only'), ('critical', 'Critical Alerts Only')], default='all', max_length=20)),
                ('send_immediate', models.BooleanField(default=False)),
                ('command_history', models.JSONField(blank=True, default=list)),
                ('scheduled_commands', models.JSONField(blank=True, default=list)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices_added', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices_device',
            },
        ),
        migrations.CreateModel(
            name='PinToggleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toggle_logs', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='PinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
                ('pin_name', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('on', 'On'), ('off', 'Off')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='devices.device')),
            ],
            options={
                'unique_together': {('device', 'pin_number')},
            },
        ),
        migrations.AddIndex(
            model_name='devicestatushistory',
            index=models.Index(fields=['device', '-changed_at'], name='devices_dev_device__599e94_idx'),
        ),
    ]
