# Generated by Django 3.2.25 on 2025-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='high_temp_threshold',
            field=models.FloatField(blank=True, help_text='Custom high temperature alert threshold for this device.', null=True),
        ),
    ]
