# Generated by Django 3.2.25 on 2025-06-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20250602_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='pintogglelog',
            name='pin_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
