# Generated by Django 3.2.25 on 2025-06-03 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_pintogglelog_pin_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pintogglelog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='pintogglelog',
            name='pin_name',
            field=models.CharField(default='Unknown Pin', max_length=50),
        ),
        migrations.AlterField(
            model_name='pintogglelog',
            name='status',
            field=models.CharField(default='off', max_length=10),
        ),
        migrations.AlterField(
            model_name='pintogglelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
