# Generated by Django 3.2.25 on 2025-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20250603_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicestatushistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='password',
        ),
        migrations.RemoveField(
            model_name='device',
            name='ssid',
        ),
        migrations.RemoveField(
            model_name='device',
            name='static_ip',
        ),
        migrations.AddField(
            model_name='devicestatushistory',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the previous status', null=True),
        ),
        migrations.AddField(
            model_name='devicestatushistory',
            name='is_confirmed',
            field=models.BooleanField(default=True, help_text='Whether this status change was confirmed'),
        ),
        migrations.AddField(
            model_name='devicestatushistory',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for status change', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='devicestatushistory',
            index=models.Index(fields=['changed_at'], name='devices_dev_changed_073971_idx'),
        ),
    ]
