# Generated by Django 3.2.25 on 2025-06-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20250604_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
                ('action', models.CharField(choices=[('on', 'On'), ('off', 'Off')], max_length=10)),
                ('scheduled_time', models.DateTimeField()),
                ('repeat', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='once', max_length=10)),
                ('is_executed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_schedules', to='devices.device')),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
