# Generated by Django 3.2.25 on 2025-05-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.CharField(choices=[('all', 'All Alerts'), ('important', 'Important Only'), ('none', 'None')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='update_interval',
            field=models.IntegerField(default=15),
        ),
    ]
